In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("E:/Urban_heat_data _analysis/india_weather_data.csv")

In [3]:
df.shape

(131055, 18)

In [4]:
df.describe()

,latitude,longitude,wind_speed,cloud_cover,precipitation_probability,pressure_surface_level,dew_point,uv_index,heatwave,visibility,rainfall,solar_radiation,snowfall,max_temperature,min_temperature,max_humidity,min_humidity
count,117910.000000,117768.000000,117886.000000,118072.000000,117821.000000,117806.000000,118175.000000,117737.000000,117855.000000,117974.000000,118006.000000,118059.000000,118006.000000,118180.000000,117942.000000,118115.000000,117925.000000
mean,20.554516,77.073179,7.512923,49.994509,49.978157,1000.062276,27.747017,6.873560,0.085682,4.497208,9.244775,464.468374,0.003390,32.765169,27.754265,61.058860,50.970356
std,7.054356,4.389530,4.343554,28.773038,28.881867,29.041733,8.916722,2.747065,0.279894,3.262718,14.098656,268.639311,0.411671,8.892352,8.901450,24.495257,24.543755
min,11.016800,72.571400,0.000131,0.000052,0.000657,500.000000,-4.686124,0.000000,0.000000,0.500008,0.000000,50.012522,0.000000,0.208974,-7.912180,10.130181,-6.605207
25%,13.082700,74.124000,3.753374,25.050978,24.909287,975.120337,22.815512,4.963394,0.000000,1.331052,0.000000,238.528091,0.000000,27.821790,22.843354,41.001376,30.825531
50%,22.572600,75.787300,7.506365,50.046934,49.884544,1000.031231,28.107669,6.974302,0.000000,5.039850,2.549558,424.262022,0.000000,33.157483,28.128994,62.156753,51.876872
75%,26.912400,77.594600,11.286737,74.934479,74.941464,1025.156797,33.496462,9.021326,0.000000,7.526562,12.445607,685.252206,0.000000,38.485091,33.472847,80.843734,70.791113
max,32.726600,88.363900,100.000000,99.999461,99.998943,1049.998522,49.897714,11.000000,1.000000,50.000000,300.000000,999.964169,50.000000,104.379272,96.475944,158.989298,146.190408

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 131055 entries, 0 to 131054
Data columns (total 18 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   date                       118202 non-null  object
 1   latitude                   117910 non-null  float64
 2   longitude                  117768 non-null  float64
 3   wind_speed                 117886 non-null  float64
 4   cloud_cover                118072 non-null  float64
 5   precipitation_probability  117821 non-null  float64
 6   pressure_surface_level     117806 non-null  float64
 7   dew_point                  118175 non-null  float64
 8   uv_index                   117737 non-null  float64
 9   heatwave                   117855 non-null  float64
 10  visibility                 117974 non-null  float64
 11  rainfall                   118006 non-null  float64
 12  solar_radiation            118059 non-null  float64
 13  snowfall                   118006 non-null  float64
 14  max_temperature            118180 non-null  float64
 15  min_temperature            117942 non-null  float64
 16  max_humidity               118115 non-null  float64
 17  min_humidity               117925 non-null  float64
dtypes: float64(17), object(1)
memory usage: 18.0+ MB

In [6]:

df.dtypes

date                          object
latitude                     float64
longitude                    float64
wind_speed                   float64
cloud_cover                  float64
precipitation_probability    float64
pressure_surface_level       float64
dew_point                    float64
uv_index                     float64
heatwave                     float64
visibility                   float64
rainfall                     float64
solar_radiation              float64
snowfall                     float64
max_temperature              float64
min_temperature              float64
max_humidity                 float64
min_humidity                 float64
dtype: object

In [7]:
#df.columns = df.columns.str.strip().str.lower().str.replace(" ","_")

In [8]:
df.isnull().sum()

date                         12853
latitude                     13145
longitude                    13287
wind_speed                   13169
cloud_cover                  12983
precipitation_probability    13234
pressure_surface_level       13249
dew_point                    12880
uv_index                     13318
heatwave                     13200
visibility                   13081
rainfall                     13049
solar_radiation              12996
snowfall                     13049
max_temperature              12875
min_temperature              13113
max_humidity                 12940
min_humidity                 13130
dtype: int64

In [9]:
missing_percent = (df.isnull().sum() / len(df)) * 100
missing_percent.sort_values(ascending=False)

uv_index                     10.162146
longitude                    10.138491
pressure_surface_level       10.109496
precipitation_probability    10.098050
heatwave                     10.072107
wind_speed                   10.048453
latitude                     10.030140
min_humidity                 10.018694
min_temperature              10.005723
visibility                    9.981306
rainfall                      9.956888
snowfall                      9.956888
solar_radiation               9.916447
cloud_cover                   9.906528
max_humidity                  9.873717
dew_point                     9.827935
max_temperature               9.824120
date                          9.807333
dtype: float64

In [10]:
df['date'] = pd.to_datetime(df['date'])

In [11]:
df.head()

,date,latitude,longitude,wind_speed,cloud_cover,precipitation_probability,pressure_surface_level,dew_point,uv_index,heatwave,visibility,rainfall,solar_radiation,snowfall,max_temperature,min_temperature,max_humidity,min_humidity
0,2023-01-01,28.6139,77.2090,0.428064,56.787047,89.803147,1003.885666,29.282458,6.353398,0.0,0.827196,34.565602,NaN,0.0,104.379272,96.475944,25.221215,17.901661
1,2023-01-01,19.0760,72.8777,13.603933,36.321945,75.198203,500.000000,NaN,6.653509,0.0,8.040858,NaN,944.176384,0.0,38.198134,32.485543,86.025179,74.403003
2,2023-01-01,12.9716,77.5946,100.000000,49.585297,60.621663,1001.774831,31.567394,5.976996,0.0,6.776773,0.212155,451.964858,0.0,37.908737,NaN,65.569945,52.094434
3,2023-01-01,22.5726,88.3639,2.785259,21.462155,38.284893,993.455514,29.974869,7.757285,0.0,5.783869,0.389140,743.226528,0.0,33.755248,32.350385,69.260757,61.289844
4,2023-01-01,NaN,80.2707,9.399230,NaN,21.538080,1020.945313,25.815398,3.376130,0.0,8.133818,0.000000,493.243162,0.0,32.172688,27.963711,81.054374,75.400783

In [12]:
df = df.dropna(subset=['date'])

In [13]:
df['rainfall'].fillna(0, inplace=True)

In [14]:
df['max_humidity'].fillna(df['max_humidity'].median(), inplace=True)
df['min_humidity'].fillna(df['min_humidity'].median(), inplace=True)
df['max_temperature'] = df['max_temperature'].fillna(df['max_temperature'].mean())
df['min_temperature'] = df['min_temperature'].fillna(df['min_temperature'].mean())
df['wind_speed'] = df['wind_speed'].fillna(df['wind_speed'].mean())
df['pressure_surface_level'] = df['pressure_surface_level'].fillna(df['pressure_surface_level'].mean())
df['visibility'] = df['visibility'].fillna(df['visibility'].median())
df['cloud_cover'] = df['cloud_cover'].fillna(df['cloud_cover'].median())
df['solar_radiation'] = df['solar_radiation'].fillna(df['solar_radiation'].mean())
df['dew_point'] = df['dew_point'].fillna(df['dew_point'].mean())
df['uv_index'] = df['uv_index'].fillna(df['uv_index'].median())
df['heatwave'] = df['heatwave'].fillna(0)
df['precipitation_probability'] = df['precipitation_probability'].fillna(
    df['precipitation_probability'].mean()
)
df['snowfall'] = df['snowfall'].fillna(0)

In [15]:
df.isnull().sum()

date                             0
latitude                     11866
longitude                    12041
wind_speed                       0
cloud_cover                      0
precipitation_probability        0
pressure_surface_level           0
dew_point                        0
uv_index                         0
heatwave                         0
visibility                       0
rainfall                         0
solar_radiation                  0
snowfall                         0
max_temperature                  0
min_temperature                  0
max_humidity                     0
min_humidity                     0
dtype: int64

In [16]:
df = df.dropna(subset=['latitude', 'longitude'])

In [17]:
df.shape

(95536, 18)

In [18]:
df.isnull().sum()

date                         0
latitude                     0
longitude                    0
wind_speed                   0
cloud_cover                  0
precipitation_probability    0
pressure_surface_level       0
dew_point                    0
uv_index                     0
heatwave                     0
visibility                   0
rainfall                     0
solar_radiation              0
snowfall                     0
max_temperature              0
min_temperature              0
max_humidity                 0
min_humidity                 0
dtype: int64

In [19]:
#df.duplicated().sum()

In [20]:
#df = df.drop_duplicates()

In [21]:
df = df.groupby(['date', 'latitude', 'longitude']).mean().reset_index()

In [22]:
df.duplicated().sum()

0

In [23]:
df.describe()

,latitude,longitude,wind_speed,cloud_cover,precipitation_probability,pressure_surface_level,dew_point,uv_index,heatwave,visibility,rainfall,solar_radiation,snowfall,max_temperature,min_temperature,max_humidity,min_humidity
count,70971.000000,70971.000000,70971.000000,70971.000000,70971.000000,70971.000000,70971.000000,70971.000000,70971.000000,70971.000000,70971.000000,70971.000000,70971.000000,70971.000000,70971.000000,70971.000000,70971.000000
mean,20.536508,77.065921,7.521065,49.938001,50.012287,1000.078690,27.770076,6.885497,0.077836,4.553295,8.377648,464.497184,0.004932,32.792796,27.771185,61.164241,51.012485
std,7.045207,4.383382,3.855308,25.657339,25.635538,25.833438,8.097754,2.436173,0.251890,2.910637,12.785584,239.362093,0.478483,8.069797,8.077854,22.807829,22.813637
min,11.016800,72.571400,0.000458,0.000052,0.002766,500.000000,-4.686124,0.000000,0.000000,0.500008,0.000000,50.013221,0.000000,0.208974,-7.912180,10.130181,-6.605207
25%,13.082700,74.124000,4.617290,30.382525,30.526210,980.682558,23.743316,5.378906,0.000000,1.567198,0.000000,281.086466,0.000000,28.718370,23.753498,43.199685,32.931849
50%,22.572600,75.787300,7.513287,50.167109,49.952160,1000.048528,27.761019,6.970117,0.000000,5.040954,2.250734,462.497421,0.000000,32.783130,27.769879,62.172560,51.857436
75%,26.912400,77.594600,10.434350,69.384772,69.601702,1019.532254,32.551708,8.569298,0.000000,6.936643,11.718523,629.202602,0.000000,37.568049,32.523810,78.931753,68.843223
max,32.726600,88.363900,100.000000,99.999461,99.998401,1049.998522,49.708882,11.000000,1.000000,50.000000,300.000000,999.910230,50.000000,104.379272,96.475944,158.989298,146.190408

In [24]:
cols = ['rainfall', 'wind_speed', 'visibility','solar_radiation','precipitation_probability','min_humidity','max_humidity']
(df[cols] < 0).sum()

rainfall                     0
wind_speed                   0
visibility                   0
solar_radiation              0
precipitation_probability    0
min_humidity                 4
max_humidity                 0
dtype: int64

In [25]:
df.loc[df['min_humidity'] < 0, 'min_humidity'] = None

In [26]:
df['min_humidity'].fillna(df['min_humidity'].median(), inplace=True)

In [27]:
(df['min_humidity'] < 0).sum()

0

In [28]:
(df[cols] < 0).sum()

rainfall                     0
wind_speed                   0
visibility                   0
solar_radiation              0
precipitation_probability    0
min_humidity                 0
max_humidity                 0
dtype: int64

In [29]:
for col in cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = ((df[col] < lower) | (df[col] > upper)).sum()
    print(col, "→ Remaining outliers:", outliers)

rainfall → Remaining outliers: 7313
wind_speed → Remaining outliers: 1
visibility → Remaining outliers: 7
solar_radiation → Remaining outliers: 0
precipitation_probability → Remaining outliers: 0
min_humidity → Remaining outliers: 6
max_humidity → Remaining outliers: 7

In [30]:
df[cols].describe()

,rainfall,wind_speed,visibility,solar_radiation,precipitation_probability,min_humidity,max_humidity
count,70971.000000,70971.000000,70971.000000,70971.000000,70971.000000,70971.000000,70971.000000
mean,8.377648,7.521065,4.553295,464.497184,50.012287,51.015780,61.164241
std,12.785584,3.855308,2.910637,239.362093,25.635538,22.809536,22.807829
min,0.000000,0.000458,0.500008,50.013221,0.002766,0.224786,10.130181
25%,0.000000,4.617290,1.567198,281.086466,30.526210,32.934588,43.199685
50%,2.250734,7.513287,5.040954,462.497421,49.952160,51.857436,62.172560
75%,11.718523,10.434350,6.936643,629.202602,69.601702,68.843223,78.931753
max,300.000000,100.000000,50.000000,999.910230,99.998401,146.190408,158.989298

In [31]:
for col in cols:
    print(col, "Min:", df[col].min(), "Max:", df[col].max())

rainfall Min: 0.0 Max: 300.0
wind_speed Min: 0.0004576399537109 Max: 100.0
visibility Min: 0.5000083530786594 Max: 50.0
solar_radiation Min: 50.013221407824446 Max: 999.9102303711336
precipitation_probability Min: 0.0027663560739465 Max: 99.9984013744908
min_humidity Min: 0.2247863004187564 Max: 146.1904077417001
max_humidity Min: 10.130180694693742 Max: 158.98929812241855

In [32]:
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
df['day'] = df['date'].dt.day

In [33]:
df[['date','year','month','day']].head()

        date  year  month  day
0 2023-01-01  2023      1    1
1 2023-01-01  2023      1    1
2 2023-01-01  2023      1    1
3 2023-01-01  2023      1    1
4 2023-01-01  2023      1    1

In [38]:
df.isnull().sum()

date                         0
latitude                     0
longitude                    0
wind_speed                   0
cloud_cover                  0
precipitation_probability    0
pressure_surface_level       0
dew_point                    0
uv_index                     0
heatwave                     0
visibility                   0
rainfall                     0
solar_radiation              0
snowfall                     0
max_temperature              0
min_temperature              0
max_humidity                 0
min_humidity                 0
year                         0
month                        0
day                          0
dtype: int64

In [39]:
df.duplicated().sum()

0

In [40]:
df.dtypes

date                         datetime64[ns]
latitude                            float64
longitude                           float64
wind_speed                          float64
cloud_cover                         float64
precipitation_probability           float64
pressure_surface_level              float64
dew_point                           float64
uv_index                            float64
heatwave                            float64
visibility                          float64
rainfall                            float64
solar_radiation                     float64
snowfall                            float64
max_temperature                     float64
min_temperature                     float64
max_humidity                        float64
min_humidity                        float64
year                                  int64
month                                 int64
day                                   int64
dtype: object

In [41]:
(df.select_dtypes(include='number') < 0).sum()

latitude                       0
longitude                      0
wind_speed                     0
cloud_cover                    0
precipitation_probability      0
pressure_surface_level         0
dew_point                    351
uv_index                       0
heatwave                       0
visibility                     0
rainfall                       0
solar_radiation                0
snowfall                       0
max_temperature                0
min_temperature              341
max_humidity                   0
min_humidity                   0
year                           0
month                          0
day                            0
dtype: int64

In [42]:
df.describe()

,latitude,longitude,wind_speed,cloud_cover,precipitation_probability,pressure_surface_level,dew_point,uv_index,heatwave,visibility,rainfall,solar_radiation,snowfall,max_temperature,min_temperature,max_humidity,min_humidity,year,month,day
count,70971.000000,70971.000000,70971.000000,70971.000000,70971.000000,70971.000000,70971.000000,70971.000000,70971.000000,70971.000000,70971.000000,70971.000000,70971.000000,70971.000000,70971.000000,70971.000000,70971.000000,70971.000000,70971.000000,70971.000000
mean,20.536508,77.065921,7.521065,49.938001,50.012287,1000.078690,27.770076,6.885497,0.077836,4.553295,8.377648,464.497184,0.004932,32.792796,27.771185,61.164241,51.015780,2023.009145,6.474137,15.599766
std,7.045207,4.383382,3.855308,25.657339,25.635538,25.833438,8.097754,2.436173,0.251890,2.910637,12.785584,239.362093,0.478483,8.069797,8.077854,22.807829,22.809536,0.095190,3.464206,8.796047
min,11.016800,72.571400,0.000458,0.000052,0.002766,500.000000,-4.686124,0.000000,0.000000,0.500008,0.000000,50.013221,0.000000,0.208974,-7.912180,10.130181,0.224786,2023.000000,1.000000,1.000000
25%,13.082700,74.124000,4.617290,30.382525,30.526210,980.682558,23.743316,5.378906,0.000000,1.567198,0.000000,281.086466,0.000000,28.718370,23.753498,43.199685,32.934588,2023.000000,3.000000,8.000000
50%,22.572600,75.787300,7.513287,50.167109,49.952160,1000.048528,27.761019,6.970117,0.000000,5.040954,2.250734,462.497421,0.000000,32.783130,27.769879,62.172560,51.857436,2023.000000,6.000000,16.000000
75%,26.912400,77.594600,10.434350,69.384772,69.601702,1019.532254,32.551708,8.569298,0.000000,6.936643,11.718523,629.202602,0.000000,37.568049,32.523810,78.931753,68.843223,2023.000000,9.000000,23.000000
max,32.726600,88.363900,100.000000,99.999461,99.998401,1049.998522,49.708882,11.000000,1.000000,50.000000,300.000000,999.910230,50.000000,104.379272,96.475944,158.989298,146.190408,2024.000000,12.000000,31.000000

In [43]:
df['max_temperature'].unique()

array([37.9087372 , 32.78313002, 38.19813356, ..., 27.53735651,
       28.03317154, 14.17369258])

In [44]:
print("Start:", df['date'].min())
print("End:", df['date'].max())

Start: 2023-01-01 00:00:00
End: 2024-01-10 00:00:00

In [45]:
df.shape

(70971, 21)

In [52]:
heatwave_counts = df.groupby(['latitude', 'longitude'])['heatwave'].sum().reset_index()

In [53]:
heatwave_counts = heatwave_counts.sort_values(by='heatwave', ascending=False)
heatwave_counts.head(10)

   latitude  longitude    heatwave
8   28.6139    77.2090  905.366667
7   26.9124    75.7873  857.800000
6   23.0225    72.5714  848.833333
3   15.2993    74.1240  674.916667
5   22.5726    88.3639  649.916667
4   19.0760    72.8777  639.800000
2   13.0827    80.2707  628.450000
9   32.7266    74.8570  319.050000
0   11.0168    76.9558    0.000000
1   12.9716    77.5946    0.000000

In [55]:
heatwave_counts.head(5)

   latitude  longitude    heatwave
8   28.6139    77.2090  905.366667
7   26.9124    75.7873  857.800000
6   23.0225    72.5714  848.833333
3   15.2993    74.1240  674.916667
5   22.5726    88.3639  649.916667

In [56]:
df['lat_bin'] = df['latitude'].round(1)
df['lon_bin'] = df['longitude'].round(1)

region_heatwave = df.groupby(['lat_bin', 'lon_bin'])['heatwave'].sum().reset_index()
region_heatwave.sort_values(by='heatwave', ascending=False).head()

   lat_bin  lon_bin    heatwave
8     28.6     77.2  905.366667
7     26.9     75.8  857.800000
6     23.0     72.6  848.833333
3     15.3     74.1  674.916667
5     22.6     88.4  649.916667

In [58]:
heatwave_counts = df.groupby(['latitude', 'longitude'])['heatwave'].sum().reset_index()

In [59]:
import folium

# Center map around India (approx)
m = folium.Map(location=[22.5, 78.9], zoom_start=5)

In [60]:
for _, row in heatwave_counts.iterrows():
    folium.CircleMarker(
        location=[row['latitude'], row['longitude']],
        radius=row['heatwave'] / 10,   # size based on heatwave count
        popup=f"Heatwaves: {row['heatwave']}",
        color='red',
        fill=True,
        fill_color='red'
    ).add_to(m)

In [61]:
m

In [62]:
df.to_csv('E:/Urban_heat_data _analysis/india_heatwave_cleaned.csv',index=False)

In [63]:
import sqlalchemy as sal

engine = sal.create_engine('mysql+pymysql://root:@localhost:3306/indiaweatheranalysis')

conn = engine.connect()
print("Connection Successful!")

Connection Successful!

In [64]:
df.to_sql('india_weather_data', con=engine, index=False, if_exists='append')

print("Done! Rows inserted:", len(df))

Done! Rows inserted: 70971